language: python

dist: focal
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
      - name: "Python 3.8"
        os: osx
        osx_image: xcode10.1
        language: shell
        addons:
          homebrew:
            packages:
              - openssl@1.1
              - python@3.8
            update: true
        env:
          - CMAKE_ARGS="-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1"

install:
  - ci/install_boost.sh
  - python3 --version
  - python3 -m pip install -U pip pytest pytest-timeout
  - python3 -m pip install cmake>=3.16 ninja qibuild>=3.15 scikit-build

script:
  - python3 setup.py bdist_wheel -- $CMAKE_ARGS -DBOOST_ROOT=$HOME/opt/boost_1_64_0
  - pushd _skbuild/*/cmake-build &&
    ctest --output-on-failure &&
    popd

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  draft: true
#  overwrite: true
