language: python

dist: focal
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
      - name: "Python 3.8 on macOS 10.13 (XCode 9.4.1)"
        os: osx
        osx_image: xcode9.4
        language: shell
        addons:
          homebrew:
            packages:
              - openssl
              - python@3.8

before_install:
  - wget -q http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download -O boost_1_64_0.tar.gz
  - tar xzf boost_1_64_0.tar.gz
  - pushd boost_1_64_0 &&
    ./bootstrap.sh --prefix=/usr/local --with-libraries=atomic,date_time,thread,chrono,filesystem,locale,regex,program_options,random &&
    ./b2 -d0 link=shared threading=multi variant=release &&
    sudo ./b2 -d0 install &&
    popd

install:
  - python3 --version
  - python3 -m pip install -U pip pytest
  - python3 -m pip install cmake>=3.16 ninja qibuild>=3.15 scikit-build

script:
  - python3 setup.py bdist_wheel
  - pushd _skbuild/*/cmake-build &&
    ctest --output-on-failure &&
    popd

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  draft: true
#  overwrite: true
